const skills = [
    "HTML",
    "CSS",
    "ReactJS",
    "NodeJS",
    "Python",
    "Front-End Development",
    "Redux.js",
    "Agile Methodologies",
    "Responsive Web Design",
    "Product Management",
    "Software Developement",
    "PHP",
    "SQL",
    "TypeScript",
    "JavaScript",
    "Data Analysis",
    "UI Design",
    "Machine Learning",
    "User Interface Design",
    "Amazon Web Services (AWS)",
    "Communication",
]

export default skills;